#Clear On Python
import os
import time
os.system('clear')
time.sleep(2)

print (" ____        _  __     _  ____      _       _ ")             
print ("|  _ \ _   _| |/ /__ _| |/ ___|   _| | __ _| |_ ___  _ __") 
print ("| |_) | | | | ' // _` | | |  | | | | |/ _` | __/ _ \| '__|")
print ("|  __/| |_| | . \ (_| | | |__| |_| | | (_| | || (_) | |")   
print ("|_|    \__, |_|\_\__,_|_|\____\__,_|_|\__,_|\__\___/|_|")   
print ("       |___/")   
print (" ")
print ("======================================")
print ("= Silahkan Pilih Operator :          =")
print ("======================================")
print ("= a) Tambah(+)            c) Kali(*) =")
print ("= b) Kurang(-)            d) Bagi(/) =")
print ("======================================")
print (" ")
Pilih = raw_input("Pilih Yang Mana Hayoo? : ")			

#Clear On Python
import os
import time
os.system('clear')
time.sleep(2)

if Pilih == "a":
	print (" _____               _           _      __   __")  
	print ("|_   _|_ _ _ __ ___ | |__   __ _| |__  / / _ \ \ ") 
	print ("  | |/ _` | '_ ` _ \| '_ \ / _` | '_ \| |_| |_| |")
	print ("  | | (_| | | | | | | |_) | (_| | | | | |_   _| |")
	print ("  |_|\__,_|_| |_| |_|_.__/ \__,_|_| |_| | |_| | |")
	print ("                                       \_\   /_/ ")
	print (" ") 
	t1 = input("Masukkan Angka Pertama : ")
	t2 = input("Masukkan Angka Kedua : ")
	print (" ")
	print ("==========- Hasilnya Adalah -==========")
	print ("Dalam Bentuk Integer :"), int(t1 + t2)
	print ("Dalam Bentuk Float :"), float(t1 + t2)
	print ("Dalam Bentuk Boolean :"), bool(t1 + t2)
	print ("=======================================")

elif Pilih == "b":
	print (" _  __                            __   __")  
	print ("| |/ /   _ _ __ __ _ _ __   __ _ / /   \ \ ") 
	print ("| ' / | | | '__/ _` | '_ \ / _` | |_____| |")
	print ("| . \ |_| | | | (_| | | | | (_| | |_____| |")
	print ("|_|\_\__,_|_|  \__,_|_| |_|\__, | |     | |")
	print ("                           |___/ \_\   /_/")
	print (" ")
	k1 = input("Masukkan Angka Pertama : ")
	k2 = input("MAsukkan Angka Kedua : ")
	print ("==========- Hasilnya Adalah -==========")
	print ("Dalam Bentuk Integer :"), int(k1 - k2)
	print ("Dalam Bentuk Float :"), float(k1 - k2)
	print ("Dalam Bentuk Boolean :"), bool(k1 - kl2)
	print ("=======================================")

elif Pilih == "c":
	print (" _  __     _ _  __    __")  
	print ("| |/ /__ _| (_)/ /_/\_\ \ ") 
	print ("| ' // _` | | | |\    /| |")
	print ("| . \ (_| | | | |/_  _\| |")
	print ("|_|\_\__,_|_|_| |  \/  | |")
	print ("               \_\    /_/")
	print (" ")
	kl1 = input("Masukkan Angka Pertama : ")
	kl2 = input("Masukkan Angka Kedua : ")
	print ("==========- Hasilnya Adalah -==========")
	print ("Dalam Bentuk Integer :"), int(kl1 * kl2)
	print ("Dalam Bentuk Float :"), float(kl1 * kl2)
	print ("Dalam Bentuk Boolean :"), bool(kl1 * kl2)
	print ("=======================================")

elif Pilih == "d":
	print (" ____              _  __  ____")  
	print ("| __ )  __ _  __ _(_)/ / / /\ \ ") 
	print ("|  _ \ / _` |/ _` | | | / /  | |")
	print ("| |_) | (_| | (_| | | |/ /   | |")
	print ("|____/ \__,_|\__, |_| /_/    | |")
	print ("             |___/   \_\    /_/")
	print (" ") 	
	b1 = input("Masukkan Angka Pertama : ")
	b2 = input("Masukkan Angka Kedua : ")
	print ("==========- Hasilnya Adalah -==========")
	print ("Dalam Bentuk Integer :"), int(b1 / b2)
	print ("Dalam Bentuk Float :"), float(b1 / b2)
	print ("Dalam Bentuk Boolean :"), bool(b1 / b2)
	print ("=======================================")

else:
	print("======================================================")
	print("= Terjadi Kesalahan Saat Mengeksekusi Program Ini..! =")
	print("= Laporkan Masalah Ini Jika Masalah Terus Muncul!    =")
	print("=====================================================")